import { readFile, stat } from 'node:fs/promises';
import { basename, dirname, join, relative, sep } from 'node:path';
import { globby } from 'globby';
import ignoreDefault from 'ignore';
import type { Ecosystem, Language, RawModule } from '@kna/ir';
import { isDeniedPath, isSkippablePath } from '@kna/scanner';

/**
 * `ignore` ships an ESM `export default` inside a CommonJS package, which NodeNext types as
 * the module namespace rather than the callable it actually is at runtime. This narrows it to
 * the surface used here rather than casting at each call site.
 */
interface IgnoreMatcher {
  add(patterns: string | string[]): IgnoreMatcher;
  ignores(path: string): boolean;
}
const ignore = ignoreDefault as unknown as () => IgnoreMatcher;

/**
 * Repo discovery — walk, language detection, module detection.
 *
 * Module detection is where §4.3 becomes concrete: a module is a `.csproj`, an npm workspace,
 * a Python package, a service. Getting this right matters more than it sounds, because module
 * is simultaneously the unit of project membership, of reindex atomicity, and of sensitivity
 * classification.
 */

export interface DiscoveredFile {
  /** Repo-relative, forward slashes. */
  path: string;
  absolutePath: string;
  language: Language;
  bytes: number;
  /** Machine-generated by path convention — demoted in retrieval (§15.5). */
  generated: boolean;
  /** Vendored or third-party — treated with extra suspicion (§10 Layer 5). */
  vendored: boolean;
}

export interface DiscoveredModule {
  module: RawModule;
  files: DiscoveredFile[];
  /** Marker file that identified it: package.json, *.csproj, pyproject.toml… */
  manifestPath: string | null;
}

export interface DiscoveryResult {
  modules: DiscoveredModule[];
  /** Files that matched nothing — reported so "why is my repo shallow?" has an answer. */
  orphanFiles: DiscoveredFile[];
  deniedPaths: string[];
  totalFiles: number;
  languages: Language[];
}

const LANGUAGE_BY_EXTENSION: Record<string, Language> = {
  '.ts': 'typescript',
  '.tsx': 'typescript',
  '.mts': 'typescript',
  '.cts': 'typescript',
  '.js': 'javascript',
  '.jsx': 'javascript',
  '.mjs': 'javascript',
  '.cjs': 'javascript',
  '.py': 'python',
  '.pyi': 'python',
  '.cs': 'csharp',
};

export function detectLanguage(path: string): Language {
  const dot = path.lastIndexOf('.');
  if (dot < 0) return 'unknown';
  return LANGUAGE_BY_EXTENSION[path.slice(dot).toLowerCase()] ?? 'unknown';
}

export interface DiscoveryOptions {
  repoRoot: string;
  exclude?: string[];
  vendored?: string[];
  generatedPatterns?: string[];
  languages?: Language[];
  /** Hard ceiling so a pathological monorepo cannot exhaust memory during discovery. */
  maxFiles?: number;
}

export async function discover(options: DiscoveryOptions): Promise<DiscoveryResult> {
  const root = options.repoRoot;
  const maxFiles = options.maxFiles ?? 200_000;

  const gitignore = await readIgnoreFile(join(root, '.gitignore'));
  const knaignore = await readIgnoreFile(join(root, '.knaignore'));
  const ig = ignore()
    .add(gitignore)
    .add(knaignore)
    .add(options.exclude ?? []);

  // Sorted, because globby returns filesystem order and nothing downstream is indifferent to
  // it. TypeScript assigns type ids in creation order and orders a union's members by those
  // ids, so the same declaration printed on two machines can come out as
  // `"development" | "test" | "production"` on one and `"production" | "development" | "test"`
  // on the other. A symbol id is derived from its signature, so that gives one declaration two
  // ids — and §7's cost model rests on re-analysing an unchanged commit producing no work.
  //
  // `maxFiles` truncates this list too, so an unsorted order could also analyse a different
  // *set* of files on a large repository.
  const entries = (
    await globby(['**/*'], {
      cwd: root,
      dot: false,
      onlyFiles: true,
      followSymbolicLinks: false,
      gitignore: false,
      ignore: ['**/node_modules/**', '**/.git/**'],
    })
  ).sort();

  const deniedPaths: string[] = [];
  const files: DiscoveredFile[] = [];
  const vendoredMatchers = compileGlobs(options.vendored ?? []);
  const generatedMatchers = compileGlobs(options.generatedPatterns ?? []);

  for (const rel of entries) {
    if (files.length >= maxFiles) break;
    const path = rel.split(sep).join('/');

    if (isDeniedPath(path)) {
      deniedPaths.push(path);
      continue;
    }
    if (isSkippablePath(path)) continue;
    if (ig.ignores(path)) continue;

    const language = detectLanguage(path);
    if (language === 'unknown' && !isInterestingNonSource(path)) continue;
    if (
      options.languages?.length &&
      language !== 'unknown' &&
      !options.languages.includes(language)
    ) {
      continue;
    }

    const absolutePath = join(root, rel);
    let bytes = 0;
    try {
      bytes = (await stat(absolutePath)).size;
    } catch {
      continue;
    }

    files.push({
      path,
      absolutePath,
      language,
      bytes,
      generated: generatedMatchers.some((m) => m.test(path)),
      vendored: vendoredMatchers.some((m) => m.test(path)),
    });
  }

  const modules = await detectModules(root, files);
  const claimed = new Set(modules.flatMap((m) => m.files.map((f) => f.path)));
  const orphanFiles = files.filter((f) => !claimed.has(f.path) && f.language !== 'unknown');

  return {
    modules,
    orphanFiles,
    deniedPaths,
    totalFiles: files.length,
    languages: [...new Set(files.map((f) => f.language).filter((l) => l !== 'unknown'))],
  };
}

/** Non-source files worth harvesting: manifests, IaC, OpenAPI documents, ADRs. */
function isInterestingNonSource(path: string): boolean {
  const name = basename(path).toLowerCase();
  return (
    name === 'package.json' ||
    name === 'pyproject.toml' ||
    name === 'setup.py' ||
    name === 'setup.cfg' ||
    name.endsWith('.csproj') ||
    name.endsWith('.fsproj') ||
    name.endsWith('.sln') ||
    name === 'go.mod' ||
    name === 'pom.xml' ||
    name === 'docker-compose.yml' ||
    name === 'docker-compose.yaml' ||
    name === 'chart.yaml' ||
    name.endsWith('.tf') ||
    name.endsWith('.bicep') ||
    /^openapi\.(json|ya?ml)$/.test(name) ||
    /^swagger\.(json|ya?ml)$/.test(name) ||
    name === 'codeowners' ||
    /\.(md|mdx)$/.test(name)
  );
}

interface ManifestInfo {
  name: string;
  ecosystem: Ecosystem;
  packageName: string | null;
  packageVersion: string | null;
  dependencies: RawModule['dependencies'];
}

async function detectModules(root: string, files: DiscoveredFile[]): Promise<DiscoveredModule[]> {
  const manifests = files.filter((f) => isManifest(f.path));
  const modules: DiscoveredModule[] = [];

  // Deepest manifest wins for a given file, so `packages/billing` claims its own sources
  // rather than the repo-root package.json claiming the whole monorepo.
  const sorted = [...manifests].sort((a, b) => depth(b.path) - depth(a.path));
  const claimed = new Set<string>();

  for (const manifest of sorted) {
    const moduleDir = dirname(manifest.path) === '.' ? '' : dirname(manifest.path);
    const info = await readManifest(join(root, manifest.path), manifest.path);
    if (!info) continue;

    const moduleFiles = files.filter(
      (f) =>
        !claimed.has(f.path) &&
        f.language !== 'unknown' &&
        (moduleDir === '' || f.path.startsWith(`${moduleDir}/`)),
    );
    if (moduleFiles.length === 0) continue;

    for (const f of moduleFiles) claimed.add(f.path);

    const owners = await readCodeowners(root, moduleDir);

    modules.push({
      manifestPath: manifest.path,
      files: moduleFiles,
      module: {
        path: moduleDir || '.',
        name: info.name,
        ecosystem: info.ecosystem,
        packageName: info.packageName,
        packageVersion: info.packageVersion,
        languages: [...new Set(moduleFiles.map((f) => f.language))],
        visibility: 'internal',
        analysisDepth: 'shallow',
        analysisNotes: [],
        owners,
        symbolCount: 0,
        fileCount: moduleFiles.length,
        dependencies: info.dependencies,
      },
    });
  }

  // Repos with no manifest at all still get one synthetic module — a shell-script repo or a
  // loose collection of Python files is still worth indexing.
  const unclaimed = files.filter((f) => !claimed.has(f.path) && f.language !== 'unknown');
  if (unclaimed.length > 0) {
    modules.push({
      manifestPath: null,
      files: unclaimed,
      module: {
        path: '.',
        name: basename(root) || 'root',
        ecosystem: 'none',
        packageName: null,
        packageVersion: null,
        languages: [...new Set(unclaimed.map((f) => f.language))],
        visibility: 'internal',
        analysisDepth: 'shallow',
        analysisNotes: ['No package manifest found; module boundary inferred from repo root'],
        owners: await readCodeowners(root, ''),
        symbolCount: 0,
        fileCount: unclaimed.length,
        dependencies: [],
      },
    });
  }

  return modules;
}

function isManifest(path: string): boolean {
  const name = basename(path).toLowerCase();
  return (
    name === 'package.json' ||
    name === 'pyproject.toml' ||
    name === 'setup.py' ||
    name.endsWith('.csproj') ||
    name.endsWith('.fsproj')
  );
}

function depth(path: string): number {
  return path.split('/').length;
}

async function readManifest(absolutePath: string, relPath: string): Promise<ManifestInfo | null> {
  const name = basename(relPath).toLowerCase();
  try {
    if (name === 'package.json') {
      const json = JSON.parse(await readFile(absolutePath, 'utf8')) as Record<string, unknown>;
      // A workspace root that declares no name and no sources of its own is not a module.
      if (!json.name && json.workspaces) return null;
      const deps = collectDeps(json);
      return {
        name: String(json.name ?? basename(dirname(relPath))),
        ecosystem: 'npm',
        packageName: json.name ? String(json.name) : null,
        packageVersion: json.version ? String(json.version) : null,
        dependencies: deps,
      };
    }

    if (name.endsWith('.csproj') || name.endsWith('.fsproj')) {
      const xml = await readFile(absolutePath, 'utf8');
      const assembly = /<AssemblyName>([^<]+)<\/AssemblyName>/.exec(xml)?.[1];
      const packageId = /<PackageId>([^<]+)<\/PackageId>/.exec(xml)?.[1];
      const version = /<Version>([^<]+)<\/Version>/.exec(xml)?.[1] ?? null;
      const projectName = basename(relPath).replace(/\.(cs|fs)proj$/i, '');
      const deps = [
        ...xml.matchAll(/<PackageReference\s+Include="([^"]+)"(?:\s+Version="([^"]+)")?/g),
      ].map((m) => ({ name: m[1]!, version: m[2] ?? null, dev: false }));
      return {
        name: assembly ?? projectName,
        ecosystem: 'nuget',
        packageName: packageId ?? assembly ?? projectName,
        packageVersion: version,
        dependencies: deps,
      };
    }

    if (name === 'pyproject.toml') {
      const toml = await readFile(absolutePath, 'utf8');
      const projectName =
        /^\s*name\s*=\s*["']([^"']+)["']/m.exec(toml)?.[1] ?? basename(dirname(relPath));
      const version = /^\s*version\s*=\s*["']([^"']+)["']/m.exec(toml)?.[1] ?? null;
      return {
        name: projectName,
        ecosystem: 'pypi',
        packageName: projectName,
        packageVersion: version,
        dependencies: [],
      };
    }

    if (name === 'setup.py') {
      const py = await readFile(absolutePath, 'utf8');
      const projectName = /name\s*=\s*["']([^"']+)["']/.exec(py)?.[1] ?? basename(dirname(relPath));
      return {
        name: projectName,
        ecosystem: 'pypi',
        packageName: projectName,
        packageVersion: null,
        dependencies: [],
      };
    }
  } catch {
    // A malformed manifest degrades to "no module here"; it never fails the run (§5).
    return null;
  }
  return null;
}

function collectDeps(json: Record<string, unknown>): RawModule['dependencies'] {
  const out: RawModule['dependencies'] = [];
  for (const [field, dev] of [
    ['dependencies', false],
    ['peerDependencies', false],
    ['devDependencies', true],
  ] as const) {
    const section = json[field];
    if (section && typeof section === 'object') {
      for (const [name, version] of Object.entries(section as Record<string, string>)) {
        out.push({ name, version: String(version), dev });
      }
    }
  }
  return out;
}

/** CODEOWNERS gives a generated document an accountable owner (§15.8). */
async function readCodeowners(root: string, moduleDir: string): Promise<string[]> {
  for (const candidate of ['CODEOWNERS', '.github/CODEOWNERS', 'docs/CODEOWNERS']) {
    try {
      const content = await readFile(join(root, candidate), 'utf8');
      const owners = matchCodeowners(content, moduleDir || '/');
      if (owners.length > 0) return owners;
    } catch {
      continue;
    }
  }
  return [];
}

export function matchCodeowners(content: string, path: string): string[] {
  const target = path.startsWith('/') ? path.slice(1) : path;
  let best: { specificity: number; owners: string[] } | null = null;

  for (const rawLine of content.split('\n')) {
    const line = rawLine.replace(/#.*$/, '').trim();
    if (!line) continue;
    const [pattern, ...owners] = line.split(/\s+/);
    if (!pattern || owners.length === 0) continue;

    const normalized = pattern.replace(/^\//, '').replace(/\/$/, '');
    const matches =
      normalized === '*' ||
      normalized === '' ||
      target === normalized ||
      target.startsWith(`${normalized}/`);

    // Last matching rule wins in CODEOWNERS, and longer patterns are more specific.
    if (matches) {
      const specificity = normalized.length;
      if (!best || specificity >= best.specificity) best = { specificity, owners };
    }
  }

  return best?.owners ?? [];
}

async function readIgnoreFile(path: string): Promise<string[]> {
  try {
    return (await readFile(path, 'utf8')).split('\n');
  } catch {
    return [];
  }
}

function compileGlobs(globs: string[]): RegExp[] {
  return globs.map((g) => {
    const escaped = g
      .split('**')
      .map((part) =>
        part
          .replace(/[.+^${}()|[\]\\]/g, '\\$&')
          .split('*')
          .join('[^/]*'),
      )
      .join('.*');
    return new RegExp(`^${escaped}$`);
  });
}

export { relative as _relative };
